### ISSUE TITLE
There is no documentation here about the "standard" plan that ships with PCF Dev

### ISSUE THREAD

**Issue by mikepc** [pivotal-cf/docs-rabbitmq-pcf#183]
As a new user of cf using PCF Dev, I'm finding that working with RabbitMQ in this environment is a bit of a maze. This document explains a few differrent service options, but I'm using the free version that ships with PCF Dev, and I have found little-to-no documentation about installing it, getting it running, and (in my case) troubleshooting it.

In my case whenever I try to access the RabbitMQ Management Dashboard, my CF server returns 404 to the browser, the route isn't recognized. My first instinct is to seek out the documentation, but It either doesn't exist or is so difficult to find that I'm lost :(.

The docs have good coverage on the paid services, but for the version that ships on PCF Dev.. :(

**Comment by ghanna2017** [comment]
@mikepc Thanks for the feedback and sorry you ran into problems. PCF Dev is a different product from RabbitMQ for PCF, so that Rabbit functionality is packaged differently in PCF Dev, and the docs in this repo can't be used for that version. I'm now enquiring with the pcfdev team to see if they have specific info on this. It may be that we need to add documentation for that version of RabbitMQ to this doc: http://docs.pivotal.io/pcf-dev/index.html. There is a story in our backlog to check this out.
Thanks!  --Gigi

**Comment by blgm** [comment]
Closing the issue as it has been answered here: https://github.com/pivotal-cf/pcfdev/issues/277
