### ISSUE TITLE
Table of rabbitmq server metrics appears below footer

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-rabbitmq-pcf#433]
As title - table at link appears below the footer

https://docs.pivotal.io/rabbitmq-cf/1-15/monitor.html#rabbitmq-metrics

**Comment by jncd** [comment]
Hi @edbyford 
Thanks so much for spotting and reporting this.
Anything you can do to dissuade engineers from making direct commits (instead of PRs) to the docs is appreciated. 
This error was a direct change from the eng team back in January.  The docs team review all PRs but we don't see changes when your team makes them as direct commits to the docs.
Jane
